### ISSUE TITLE
Auth0/Fauna free plan doesn't support create access provider feature?

### ISSUE THREAD

**Issue by dominwong4** [fauna-labs/faunadb-auth-skeleton-with-auth0#2]
when you run `npm run setup` with auth0 free plan account

[ Failed  ] 'provider - auth0 provider', with error: [BadRequest: feature not available] {
  description: "The feature 'Create Access Providers' is not available for your plan."....blablablabla.....

**Comment by dominwong4** [comment]
May be the free tier of fauna?
I am not sure yet, cause I followed the code and It should be fail on running FQL.

So it may be faundb tier problem

**Comment by fauna-brecht** [comment]
You found this quickly, I have put it on public to make sure not to forget it when the blog post goes live.  
The features are currently only accessible on the preview environment (there was a beat for users that were interested who could test it out there), preview is a new environment for which an announcement will go out shortly. The feature will be available in production shortly as well. The blog post that goes along with this skeleton will also go out shortly. 

About pricing: Auth integration will be a paid feature as far as I know, however there will be a trial period to test it out if you are interested.

**Comment by dominwong4** [comment]
> You found this quickly, I have put it on public to make sure not to forget it when the blog post goes live.
> The features are currently only accessible on the preview environment (there was a beat for users that were interested who could test it out there), preview is a new environment for which an announcement will go out shortly. The feature will be available in production shortly as well. The blog post that goes along with this skeleton will also go out shortly.
> 
> About pricing: Auth integration will be a paid feature as far as I know, however there will be a trial period to test it out if you are interested.

I see, haha...
Fair enough if it is paid plan. Auth always is a tough problem to start the project haha. can't wait to see it on production!

**Comment by fauna-brecht** [comment]
fyi:

>npm run setup 

will work normally if you run npm install in the root folder. I defined that optional in the temporary README.md though so that definitely is wrong 👍, thanks for letting me know, I'll change that.
